# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: rm -rf node_modules && yarn install --frozen-lockfile
      - name: Setup MongoDB Atlas
        env:
          MONGODB_ATLAS_USERNAME: ${{ secrets.MONGODB_ATLAS_USERNAME }}
          MONGODB_ATLAS_PASSWORD: ${{ secrets.MONGODB_ATLAS_PASSWORD }}
          MONGODB_ATLAS_CONNECTION_STRING: ${{ secrets.MONGODB_ATLAS_CONNECTION_STRING }}
        run: |
          echo "Setting up MongoDB Atlas..."
          curl -o mongo.tar https://fastdl.mongodb.org/tools/db/mongodb-database-tools-100.5.0-linux-x86_64.tar
          tar -xvf mongo.tar
          export PATH=$PATH:`pwd`/mongodb-database-tools-100.5.0/bin
          mongo $MONGODB_ATLAS_CONNECTION_STRING --username $MONGODB_ATLAS_USERNAME --password $MONGODB_ATLAS_PASSWORD --eval "db.stats()"
      - run: yarn run build
      - run: yarn run test
